apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ilcms-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: {{ .Values.global.domain }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: ilcms-api
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ilcms-frontend
                port:
                  number: 3000
    - host: {{ .Values.global.authDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ilcms-keycloak
                port:
                  number: 8080
